export const mockData = [
  {
    id: 1,
    firstName: "Andreana",
    lastName: "Scheu",
    email: "ascheu0@vkontakte.ru",
    gender: "Female",
  },
  {
    id: 2,
    firstName: "Cary",
    lastName: "Whitlaw",
    email: "cwhitlaw1@csmonitor.com",
    gender: "Male",
  },
  {
    id: 3,
    firstName: "Barbe",
    lastName: "Halfhead",
    email: "bhalfhead2@psu.edu",
    gender: "Female",
  },
  {
    id: 4,
    firstName: "Cari",
    lastName: "Sex",
    email: "csex3@naver.com",
    gender: "Female",
  },
  {
    id: 5,
    firstName: "Logan",
    lastName: "Jakeman",
    email: "ljakeman4@intel.com",
    gender: "Male",
  },
  {
    id: 6,
    firstName: "Parker",
    lastName: "Mewett",
    email: "pmewett5@51.la",
    gender: "Male",
  },
  {
    id: 7,
    firstName: "Annadiana",
    lastName: "Gavey",
    email: "agavey6@smh.com.au",
    gender: "Female",
  },
  {
    id: 8,
    firstName: "Darsie",
    lastName: "Catherall",
    email: "dcatherall7@biglobe.ne.jp",
    gender: "Female",
  },
  {
    id: 9,
    firstName: "Tully",
    lastName: "Iskowicz",
    email: "tiskowicz8@pcworld.com",
    gender: "Male",
  },
  {
    id: 10,
    firstName: "Rosie",
    lastName: "Bliss",
    email: "rbliss9@techcrunch.com",
    gender: "Female",
  },
  {
    id: 11,
    firstName: "Fionnula",
    lastName: "Caltun",
    email: "fcaltuna@so-net.ne.jp",
    gender: "Female",
  },
  {
    id: 12,
    firstName: "Kai",
    lastName: "Bindon",
    email: "kbindonb@youku.com",
    gender: "Female",
  },
  {
    id: 13,
    firstName: "Rosco",
    lastName: "Dimblebee",
    email: "rdimblebeec@pagesperso-orange.fr",
    gender: "Male",
  },
  {
    id: 14,
    firstName: "Jory",
    lastName: "Gutans",
    email: "jgutansd@mapquest.com",
    gender: "Male",
  },
  {
    id: 15,
    firstName: "Leo",
    lastName: "Learmonth",
    email: "llearmonthe@delicious.com",
    gender: "Male",
  },
  {
    id: 16,
    firstName: "Calida",
    lastName: "Hinkens",
    email: "chinkensf@technorati.com",
    gender: "Female",
  },
  {
    id: 17,
    firstName: "Viviene",
    lastName: "Kristufek",
    email: "vkristufekg@gnu.org",
    gender: "Female",
  },
  {
    id: 18,
    firstName: "Sayres",
    lastName: "MacWhan",
    email: "smacwhanh@godaddy.com",
    gender: "Male",
  },
  {
    id: 19,
    firstName: "Dalenna",
    lastName: "Prydie",
    email: "dprydiei@globo.com",
    gender: "Female",
  },
  {
    id: 20,
    firstName: "Querida",
    lastName: "Ingerson",
    email: "qingersonj@sitemeter.com",
    gender: "Female",
  },
  {
    id: 21,
    firstName: "Bengt",
    lastName: "Bruckner",
    email: "bbrucknerk@bloomberg.com",
    gender: "Male",
  },
  {
    id: 22,
    firstName: "Happy",
    lastName: "Comellini",
    email: "hcomellinil@over-blog.com",
    gender: "Female",
  },
  {
    id: 23,
    firstName: "Kirsteni",
    lastName: "Ridgley",
    email: "kridgleym@sun.com",
    gender: "Female",
  },
  {
    id: 24,
    firstName: "Dru",
    lastName: "Ealden",
    email: "dealdenn@shutterfly.com",
    gender: "Male",
  },
  {
    id: 25,
    firstName: "Kristan",
    lastName: "Itzhak",
    email: "kitzhako@goo.ne.jp",
    gender: "Female",
  },
];
